replicaCount: 1

resources:
  requests:
    memory: "256Mi"  
    cpu: "200m"      
  limits:
    memory: "512Mi"  
    cpu: "500m"      

backend:
  image: "hadil0505/backend-image:latest"
  port: 8080
  environment:
    DB_HOST: "mysql"
    DB_USER: "root"
    DB_PASSWORD: "root-password"  
    DB_NAME: "testdb"

frontend:
  image: "hadil0505/frontend-image:latest"
  port: 8081

mysql:
  image: "mysql:8.0"
  port: 3306
  database: "testdb"
  rootPassword: "root-password"
  storageSize: "5Gi"
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"    
    limits:
      memory: "512Mi"
      cpu: "500m"    

ingress:
  enabled: true
  hostname: "myapp.workerbase.io"

persistentVolume:
  storageClassName: "standard"

networkPolicy:
  enabled: true
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 8081
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 8080

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
