apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-backend-mysql
spec:
  podSelector: {}  # Applies to all pods in the namespace

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend  # Allow traffic from frontend to backend
      ports:
        - protocol: TCP
          port: 3001  # Backend service port (to allow traffic to backend)

    - from:
        - podSelector:
            matchLabels:
              app: backend  # Allow traffic from backend to MySQL
      ports:
        - protocol: TCP
          port: 3306  # MySQL service port (to allow traffic to MySQL)